name: Build binaries for terraform and providers
on:
  - push
env:
  TFVERSION: "0.14.11"
  AWSPRVERSION: "3.72.0"
  AZUREPRVERSION: "2.95.0"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repover: [ {repo: "hashicorp/terraform", version: "${{ env.TFVERSION }}"},
            {repo: "hashicorp/terraform-provider-azurerm", version: "${{ env.AZUREPRVERSION }}"}, 
            {repo: "hashicorp/terraform-provider-aws", version: "${{ env.AWSPRVERSION }}"}]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2' # The Go version to download (if necessary) and use.
      - run: go version

      - name: zeitgeist validate
        run: ./hack/verify-dependencies.sh
      
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ matrix.reporver.repo }}
          tag: "v${{ matrix.reporver.repo }}"
          tarball: true


      - run: |
          ls
          mkdir ./${{ matrix.reporver.repo }}
          tar -xf terraform*.tar.gz -C ./${{ matrix.reporver.repo }}
          ls ./${{ matrix.reporver.repo }}
        name: Extract ${{ matrix.reporver.repo }} source

      - name: Build ${{ matrix.reporver.repo }} for GOOS=android GOARCH=arm64 
        run: |
          echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/${{ matrix.reporver.repo }}/hashicorp-terraform*
          
          #git status
          #cat ./.go-version
          
          GOOS=android GOARCH=arm64 go build -o $GITHUB_WORKSPACE/bin/${{ matrix.reporver.repo }}          
          ls $GITHUB_WORKSPACE/bin

