name: Build and Publish terraform and providers

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2' # The Go version to download (if necessary) and use.
      - run: go version

      - name: Check out terraform repo
        uses: actions/checkout@v2
        with:
          repository: hashicorp/terraform
          path: ./terraform
          ref: v0.15

      - name: Build terraform for GOOS=android GOARCH=arm64 
        run: |
          echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/terraform
          git status
          #cat ./.go-version
          GOOS=android GOARCH=arm64 go build -o $GITHUB_WORKSPACE/bin/terraform          
          ls $GITHUB_WORKSPACE/bin

      - name: Check out azurerm provider repo
        uses: actions/checkout@v2
        with:
          repository: hashicorp/terraform-provider-azurerm
          path: ./terraform-provider-azurerm

      - name: Build terraform-provider-azurerm for GOOS=android GOARCH=arm64 
        run: |
          cd $GITHUB_WORKSPACE/terraform-provider-azurerm
          git status
          #cat ./.go-version
          GOOS=android GOARCH=arm64 go build -o $GITHUB_WORKSPACE/bin/terraform-provider-azurerm          
          ls $GITHUB_WORKSPACE/bin

      - name: Check out aws provider repo
        uses: actions/checkout@v2
        with:
          repository: hashicorp/terraform-provider-aws
          path: ./terraform-provider-aws

      - name: Build terraform-provider-aws for GOOS=android GOARCH=arm64 
        run: |
          cd $GITHUB_WORKSPACE/terraform-provider-aws
          git status
          #cat ./.go-version
          GOOS=android GOARCH=arm64 go build -o $GITHUB_WORKSPACE/bin/terraform-provider-aws          
          ls $GITHUB_WORKSPACE/bin          