name: Build and Publish terraform and providers

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out tf repo
        uses: actions/checkout@main
        with:
          repository: hashicorp/terraform
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2' # The Go version to download (if necessary) and use.
      - run: go version
      - run: |
          pwd
          ls
          cd terraform
          git checkout v1.1
          cat ./.go-version
          GOOS=android GOARCH=arm64 go build -o bin/terraform          
